# Generated by Django 5.2.14 on 2026-05-21 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalog', '0003_remove_flowerstock_stock_manager'),
        ('orders', '0002_alter_stockupdate_stock_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('client', 'Client'), ('seller', 'Vendeur'), ('delivery', 'Livreur')], default='client', max_length=20),
        ),
        migrations.DeleteModel(
            name='StockManagerProfile',
        ),
    ]
