# Generated by Django 5.2.14 on 2026-05-17 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Bouquet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('soldout', 'Épuisé'), ('hidden', 'Masqué')], default='available', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bouquets', to='accounts.sellerprofile')),
                ('categories', models.ManyToManyField(blank=True, related_name='bouquets', to='catalog.category')),
            ],
        ),
        migrations.CreateModel(
            name='BouquetImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='bouquets/')),
                ('is_cover', models.BooleanField(default=False)),
                ('bouquet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.bouquet')),
            ],
        ),
        migrations.CreateModel(
            name='FlowerStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flower_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('unit', models.CharField(choices=[('stem', 'Tige'), ('bunch', 'Bouquet'), ('pot', 'Pot'), ('kg', 'Kilogramme')], default='stem', max_length=10)),
                ('min_threshold', models.PositiveIntegerField(default=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='flowers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flower_stocks', to='accounts.stockmanagerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='BouquetFlower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('bouquet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.bouquet')),
                ('flower_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.flowerstock')),
            ],
            options={
                'unique_together': {('bouquet', 'flower_stock')},
            },
        ),
        migrations.AddField(
            model_name='bouquet',
            name='flowers',
            field=models.ManyToManyField(blank=True, related_name='used_in', through='catalog.BouquetFlower', to='catalog.flowerstock'),
        ),
    ]
