# Generated by Django 5.2.14 on 2026-05-21 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flowerstock',
            name='stock_manager',
        ),
    ]
