# Generated by Django 5.2.14 on 2026-05-21 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockupdate',
            name='stock_manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_updates', to=settings.AUTH_USER_MODEL),
        ),
    ]
