# Generated by Django 5.2.14 on 2026-05-21 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_stockupdate_stock_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('on_delivery', 'à la livraison')], default='on_delivery', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('on_delivery', 'à la livraison')], max_length=20),
        ),
    ]
